# Ansible managed
---
version: "3.7"
services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    networks:
      - web
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yaml:/dynamic.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`monitor.hay-kot.dev`)
      - traefik.http.routers.api.entrypoints=dashboard
      - traefik.http.routers.api.service=api@internal
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic.yaml"
      - "--providers.file.watch=true"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secured.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=hay-kot@pm.me"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: always

networks:
  web:
    external: True
