http:
  routers:
    to-portfolio:
      rule: "Host(`hay-kot.dev`)"
      service: portfolio
      tls:
        certResolver: "mytlschallenge"

    to-next-docs:
      rule: "(Host(`mealie.hay-kot.dev`) && PathPrefix(`/nightly{regex:$$|/.*}`))"
      service: next-docs
      middlewares:
        - "nightly-stripprefix"
      tls:
        certResolver: "mytlschallenge"

  middlewares:
    nightly-stripprefix:
      stripPrefix:
        prefixes:
          - "/nightly"
    mealie-io-redirect:
      redirectRegex:
        regex: "https://mealie-demo.hay-kot.dev(.*)"
        replacement: "https://demo.mealie.io${1}"

  services:
    portfolio:
      loadBalancer:
        servers:
          - url: "https://awesome-sinoussi-2af10c.netlify.app"
    next-docs:
      loadBalancer:
        servers:
          - url: "https://mealie-nightly-docs.netlify.app"
