---
- name: Ensure Traefik Directories Exist
  file:
    path: "{{docker_dir}}/traefik"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Copy Dynamic File
  ansible.builtin.copy:
    src: "{{ traefik_dynamic }}"
    dest: "{{docker_dir}}/traefik/dynamic.yaml"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Generate Traefik Stack
  include_role:
    name: _docker_compose_generator
  vars:
    compose_dest: "{{docker_dir}}/traefik/"
    networks:
      - name: web
        external: true
    containers:
      - service_name: traefik
        container_name: traefik
        active: true
        image: traefik:v2.5
        restart: always
        ports:
          - "80:80"
          - "443:443"
        command:
          #### These are the CLI commands that will configure Traefik and tell it how to work! ####
          ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
          - --api.insecure=false # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
          - --api.dashboard=false # <== Enabling the dashboard to view services, middlewares, routers, etc...
          - --api.debug=false # <== Enabling additional endpoints for debugging and profiling
          ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
          - --log.level=ERROR # <== Setting the level of the logs from traefik
          ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
          - --providers.docker=true # <== Enabling docker as the provider for traefik
          - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
          - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
          - --providers.file.watch=true
          - --providers.docker.network=web # <== Operate on the docker network named web
          ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
          - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
          - --entrypoints.web.http.redirections.entryPoint.to=web-secured
          - --entrypoints.web.http.redirections.entryPoint.scheme=https
          - --entrypoints.web-secured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
          ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
          - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
          - --certificatesresolvers.mytlschallenge.acme.email={{ main_email }} # <== Setting email for certs
          - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
        volumes:
          - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
          - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
          - ./dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
        networks:
          - web # <== Placing traefik on the network named web, to access containers on this network
