---
- name: Ensure Mealie-Next Directories Exist
  file:
    path: "{{docker_dir}}/mealie-next"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Generate Mealie-Next Stack
  include_role:
    name: _docker_compose_generator
  vars:
    compose_dest: "{{docker_dir}}/mealie-next/"
    networks:
      - name: web
        external: true
    containers:
      - service_name: mealie-frontend
        container_name: mealie-frontend
        active: true
        image: hkotel/mealie:frontend-nightly
        networks:
          - web
        restart: always
        #    ports:
        #      - 9091:3000
        environment:
          - GLOBAL_MIDDLEWARE=auth
          - SUB_PATH=/demo/
          - ALLOW_SIGNUP=true
          - API_URL=http://mealie-api:9000
        labels:
          - "traefik.enable=true" # <== Enable traefik to proxy this container
          - "traefik.http.routers.web.middlewares=redirect@file" # <== This is a middleware to redirect to https
          - "traefik.http.routers.mealie-demo-web-secured.rule=(Host(`mealie.{{ primary_domain }}`) && PathPrefix(`/demo{regex:$$|/.*}`))" # <== Your Domain Name for the https rule
          - "traefik.http.routers.mealie-demo-web-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
          - "traefik.http.routers.mealie-demo-web-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

      - service_name: mealie-frontend
        container_name: mealie-frontend
        active: true
        image: hkotel/mealie:api-nightly
        restart: always
        networks:
          - web
        volumes:
          - ./data/:/app/data
        #    ports:
        #      - 9092:80
        environment:
          # DB_ENGINE: postgres # Optional: 'sqlite', 'postgres'
          # POSTGRES_USER: mealie
          # POSTGRES_PASSWORD: mealie
          # POSTGRES_SERVER: postgres
          # POSTGRES_PORT: 5432
          # POSTGRES_DB: mealie
          # WORKERS_PER_CORE: 0.5
          MAX_WORKERS: 1
          WEB_CONCURRENCY: 1
