---
- name: Ensure Gotify Directories Exist
  file:
    path: "{{ adguard_docker_directory }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Generate Gotify Stack
  include_role:
    name: _docker_compose_generator
  vars:
    compose_dest: "{{ adguard_docker_directory }}/"
    networks:
      - name: web
        external: true
    containers:
      - service_name: adguard
        container_name: adguard
        active: true
        # Compose Variables
        image: adguard/adguardhome
        ports:
          - 53:53/tcp
          - 53:53/udp
          - 784:784/udp
          - 853:853/tcp
          - 3788:3000/tcp
        volumes:
          - "{{ adguard_docker_directory }}/workdir:/opt/adguardhome/work"
          - "{{ adguard_docker_directory }}/confdir:/opt/adguardhome/conf"
        restart: unless-stopped

- name: Create and Start Gotify
  community.docker.docker_compose:
    restarted: true
    project_src: "{{ adguard_docker_directory }}"
  register: output
