- name: apply local configuration to servers listed in hosts
  hosts: main_docker
  user: "{{ main_username }}"
  vars_files:
    - "vars/vault.yaml"
  roles:
    - docker_onedev
    - docker_adguard
